= Building LISP
Leo Howel <leo@lwh.jp>
v1.0, 2021-01-16
:doctype: book
:sectnums:
:sectnumlevels: 5
:partnums:
:toc: right

:sectnums!:
== Contents
<<Introduction,Chapter 1: Introduction>>

<<Data,Chapter 2: Data>>

<<Parser,Chapter 3: Parser>>

<<Expressions,Chapter 4: Expressions>>

<<Built-in functions,Chapter 5: Built-in functions>>

<<Arithmetic,Chapter 6: Arithmetic>>

<<Lambda expressions and closures,Chapter 7: Lambda expressions and closures>>

<<Booleans and short-circuit evaluation,Chapter 8: Booleans and short-circuit evaluation>>

<<Syntactic sugar,Chapter 9: Syntactic sugar>>

<<Variadic functions,Chapter 10: Variadic functions>>

<<Macros,Chapter 11: Macros>>

<<Library,Chapter 12: Library>>

<<Quasiquotation,Chapter 13: Quasiquotation>>

<<Continuations and tail recursion,Chapter 14: Continuations and tail recursion>>

<<Garbage collection,Chapter 15: Garbage collection>>

<<Where do we go from here?,Chapter 16: Where do we go from here?>>

Questions? Comments? Email leo@lwh.jp.

== Copyright

    Copyright (c) by Leo Howell. All rights reserved.

This document was copied from the https://www.lwh.jp/lisp/index.html[original] and converted to AsciiDoc on 2021-01-16.

Please file an issue with the https://github.com/mdhender/bel[GitHub repository] if you find any errors with my transcription.

== Introduction
The best way to understand how something works is to try to build it for yourself. Reading somebody else's explanation might satisfy your curiosity, but without the experience of falling into all the little traps it is difficult to get a feel for why something is designed a certain way.

It's been said that every would-be programmer should write a compiler. While I think this is good advice (although I haven't followed it myself), there is so much effort involved just in parsing a language such as C that any potential insights risk getting lost in a mire of details. Perhaps creating an interpreter for some simple language would be a good first step.

I first started playing around with LISP a good few years ago, yet much later than I should have. This led me to the classic lecture series http://groups.csail.mit.edu/mac/classes/6.001/abelson-sussman-lectures/[Structure and Interpretation of Computer Programs]. If you have the next 24 hours free and haven't seen the videos already, go watch them now.

The course covers many topics, but the second half shows in detail how to evaluate LISP, first by implementing a simple version of eval in LISP itself. I figured that this would translate well into C, and so decided to try creating my own implementation of LISP.

It was really easy.

This article is an attempt to share the process by which I built my implementation, and the chapters occur roughly in the order in which I did things. Why not follow along and create your own version in your language of choice?
footnote:[If you are using a fancy language which supports something like eval, it would be cool to expose the native datatypes to the LISP environment.]

As a professional programmer (ha, ha), I spend the majority of my time writing C and C++. Most of the rest is Java. There are many languages out there, each with their own debatable merits, but I'd like to demonstrate just how simple a LISP machine can be — even built in as low-level a language as C. See John McCarthy's http://www-formal.stanford.edu/jmc/history/lisp/lisp.html[History of LISP] for the story of the pioneers.

So here is my toy implementation of LISP. I've borrowed features from various dialects, but it's closer to Scheme than Common LISP. The differences are trivial enough that changing over would not require substantial changes to the interpreter. Don't worry if you're not familiar with LISP; I will define everything as I go along.

It is not meant to be the smallest possible implementation, nor the most efficient, nor the most complete; it could however be described as lazy. My goal was to write robust, easy-to-read code that does exactly what it needs to, and no more, and I hope that it conveys how little effort is required to construct an incredibly powerful environment like LISP.

== Data
We will define four kinds of object to begin with:

Integer::
A number. For example: 3, -9, 0.
Symbol::
A name consisting of a string of characters. For example: FOO, BAR, ADD-TWO. We will normalize characters to upper-case in this project, but this is not strictly necessary.
NIL::
Represents "nothing". A bit like NULL in C and other languages.
Pair::
A pair consists of two elements, which for historical reasons are called car and cdr. Both can hold either an integer, a symbol, NIL, or a reference to another pair. The types of each element may be different.

Integers, symbols and NIL are called simple data. The term atom can refer to either a simple datum or a pair (purists may disagree on this point).

Note that integers and symbols are immutable, so we can think of two integers with the same value as being the same object. This is particularly useful for symbols, because it allows us to test for equality by comparing pointers.

=== Implementation
Let's declare some C types to hold our data. There are many clever ways to store LISP objects efficiently, but for this implementation we will stick to a very simple scheme [please excuse the pun].

[source,c]
----
struct Atom {
	enum {
		AtomType_Nil,
		AtomType_Pair,
		AtomType_Symbol,
		AtomType_Integer
	} type;

	union {
		struct Pair *pair;
		const char *symbol;
		long integer;
	} value;
};

struct Pair {
	struct Atom atom[2];
};

typedef struct Atom Atom;
----

A few macros will be handy:

[source,c]
----
#define car(p) ((p).value.pair->atom[0])
#define cdr(p) ((p).value.pair->atom[1])
#define nilp(atom) ((atom).type == AtomType_Nil)

static const Atom nil = { AtomType_Nil };
----

The "p" in `nilp` stands for "predicate". Identifiers in C may not contain question marks. There is no need to restrict our LISP implementation in that way, of course.

Integers and (pointers to) strings can be copied around, but we need to allocate pairs on the heap.

[source,c]
----
Atom cons(Atom car_val, Atom cdr_val)
{
	Atom p;

	p.type = AtomType_Pair;
	p.value.pair = malloc(sizeof(struct Pair));

	car(p) = car_val;
	cdr(p) = cdr_val;

	return p;
}
----

`cons` is a function to allocate a pair on the heap and assign its two elements.

At this point you will have noticed that using `cons` will leak memory the moment its return value is discarded. We will deal with that later. Of course, if you are using a garbage-collected language then the problem is already taken care of.

=== Testing
Now we can start creating LISP objects. An integer:

[source,c]
----
Atom make_int(long x)
{
	Atom a;
	a.type = AtomType_Integer;
	a.value.integer = x;
	return a;
}
----

And a symbol:

[source,c]
----
Atom make_sym(const char *s)
{
	Atom a;
	a.type = AtomType_Symbol;
	a.value.symbol = strdup(s);
	return a;
}
----

=== Textual representation
We will write a pair like this:

[source,lisp]
----
(a . b)
----

where a is the car and b is the cdr.

By using the cdr of a pair to reference another pair, we can create a chain:

[source,lisp]
----
(a . (b . (c . (d . NIL))))
----

Notice that the cdr of the last pair is NIL. This signifies the end of the chain, and we call this structure a list. To avoid having to write a large number of brackets, we will write the previous list like this:

[source,lisp]
----
(a b c d)
----

Finally, if the cdr of the last pair in a list is not NIL, we will write this:
[source,lisp]
----
(p q . r)
----
which is equivalent to
[source,lisp]
----
(p . (q . r))
----
This is called an improper list.

=== Implementation
Printing an atom or list is simple.

[source,c]
----
void print_expr(Atom atom)
{
    switch (atom.type) {
    case AtomType_Nil:
        printf("NIL");
        break;
    case AtomType_Pair:
        putchar('(');
        print_expr(car(atom));
        atom = cdr(atom);
        while (!nilp(atom)) {
            if (atom.type == AtomType_Pair) {
                putchar(' ');
                print_expr(car(atom));
                atom = cdr(atom);
            } else {
                printf(" . ");
                print_expr(atom);
                break;
            }
        }
        putchar(')');
        break;
    case AtomType_Symbol:
        printf("%s", atom.value.symbol);
        break;
    case AtomType_Integer:
        printf("%ld", atom.value.integer);
        break;
    }
}
----

By using recursion we can print aribtrarily complex data structures. (Actually that's not true: for a very deeply nested structure we will run out of stack space, and a self-referencing tree will never finish printing).

=== Testing
See what print_expr does with various atoms:

|===
|Atom|Output

|make_int(42)|42
|make_sym("FOO")|FOO
|cons(make_sym("X"), make_sym("Y"))|(X . Y)
|cons(make_int(1),cons(make_int(2),cons(make_int(3),nil)))|(1 2 3)
|===

All this is pretty trivial. We'll get on to some more interesting stuff in the next chapter.

=== One last thing
Remember we said that we would treat identical symbols as being the same object? We can enforce that by keeping track of all the symbols created, and returning the same atom if the same sequence of characters is requested subsequently.

Languages with a set or hashtable container make this easy, but we can use the LISP data structures already implemented to store the symbols in a list:

[source,c]
----
static Atom sym_table = { AtomType_Nil };

Atom make_sym(const char *s)
{
    Atom a, p;

	p = sym_table;
	while (!nilp(p)) {
		a = car(p);
		if (strcmp(a.value.symbol, s) == 0)
			return a;
		p = cdr(p);
	}

	a.type = AtomType_Symbol;
	a.value.symbol = strdup(s);
	sym_table = cons(a, sym_table);

	return a;
}
----

Neat, huh? It's not particularly efficient, but it will do fine for now.

== Parser

== Expressions

== Built-in functions

== Arithmetic

== Lambda expressions and closures

== Booleans and short-circuit evaluation

== Syntactic sugar

== Variadic functions

== Macros

== Library

== Quasiquotation

== Continuations and tail recursion

== Garbage collection

== Where do we go from here?
